name: Run CreateNewCountry Project on Schedule

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Adjust to your .NET version

      # Step 3: Cache .NET dependencies
      - name: Cache .NET dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ./.nuget
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }} # Cache key based on the project files
          restore-keys: |
            ${{ runner.os }}-dotnet-

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Build the solution
      - name: Build solution
        run: dotnet build --no-restore

      # Step 6: Run CreateNewCountry project
      - name: Run CreateNewCountry program
        run: dotnet run --project TestGithubActions/TestGithubActions.csproj
